apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app2: nginx
  name: nginx
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: akkayaumut/count-fastapi:latest
        name: nginx
        resources:
          limits:
            cpu: "1000m"
            memory: "250Mi"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nginx
              topologyKey: ucloud.com/zone


